# paths:
log_path: "./logs/discord.log"
chat_db_path: "./data/chat.db"

# rounding:
temperature_rounding: 1
currency_perc_rounding: 1

# timeframe for message context to be used for the GPT model in hours
chat_history_timeframe: 0.5
